In [57]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("Assessment-III.csv")

In [58]:
df

,customer_id,age,annual_income_usd,spending_score,website_visits_per_month,avg_purchase_value_usd,days_since_last_purchase
0,C001,26.0,30530.0,38,25.0,NaN,44.0
1,C002,23.0,NaN,51,29.0,56.92,65.0
2,C003,NaN,27749.0,16,28.0,NaN,53.0
3,C004,30.0,NaN,37,26.0,22.72,35.0
4,C005,23.0,15000.0,38,20.0,83.39,38.0
...,...,...,...,...,...,...,...
195,C196,48.0,116955.0,93,4.0,465.35,21.0
196,C197,43.0,NaN,88,3.0,476.41,17.0
197,C198,38.0,143584.0,79,13.0,607.51,23.0
198,C199,43.0,NaN,71,6.0,479.89,19.0
199,C200,49.0,115590.0,86,9.0,403.14,31.0

In [59]:
df.columns

Index(['customer_id', 'age', 'annual_income_usd', 'spending_score',
       'website_visits_per_month', 'avg_purchase_value_usd',
       'days_since_last_purchase'],
      dtype='object')

In [60]:
def fill(df, column):
    skewness = df[column].skew()
    if skewness < -0.5 or skewness > 0.5:
        df[column].fillna(df[column].median(), inplace=True)
    else:
        df[column].fillna(df[column].mean(), inplace=True)
        print(f"Filled missing values in {column} with mean.")

df["annual_income_usd"] = pd.to_numeric(df["annual_income_usd"])
df["age"] = pd.to_numeric(df["age"])
df["spending_score"] = pd.to_numeric(df["spending_score"])
df["website_visits_per_month"] = pd.to_numeric(df["website_visits_per_month"])
df["avg_purchase_value_usd"] = pd.to_numeric(df["avg_purchase_value_usd"])
df["days_since_last_purchase"] = pd.to_numeric(df["days_since_last_purchase"])



fill(df, "annual_income_usd")
fill(df, "age")
fill(df, "spending_score")
fill(df, "website_visits_per_month")
fill(df, "avg_purchase_value_usd")
fill(df, "days_since_last_purchase")

Filled missing values in age with mean.
Filled missing values in spending_score with mean.
Filled missing values in website_visits_per_month with mean.

C:\Users\HP\AppData\Local\Temp\ipykernel_34344\3491442470.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].median(), inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_34344\3491442470.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_34344\3491442470.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].median(), inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_34344\3491442470.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].median(), inplace=True)

In [61]:
df

,customer_id,age,annual_income_usd,spending_score,website_visits_per_month,avg_purchase_value_usd,days_since_last_purchase
0,C001,26.000000,30530.0,38,25.0,164.615,44.0
1,C002,23.000000,61616.5,51,29.0,56.920,65.0
2,C003,36.630435,27749.0,16,28.0,164.615,53.0
3,C004,30.000000,61616.5,37,26.0,22.720,35.0
4,C005,23.000000,15000.0,38,20.0,83.390,38.0
...,...,...,...,...,...,...,...
195,C196,48.000000,116955.0,93,4.0,465.350,21.0
196,C197,43.000000,61616.5,88,3.0,476.410,17.0
197,C198,38.000000,143584.0,79,13.0,607.510,23.0
198,C199,43.000000,61616.5,71,6.0,479.890,19.0
199,C200,49.000000,115590.0,86,9.0,403.140,31.0

In [62]:
df["annual_income_scaled"] = ((df["annual_income_usd"]-df["annual_income_usd"].min())/(df["annual_income_usd"].max() - df["annual_income_usd"].min()))

df["age_scaled"] = ((df["age"] - df["age"].min())/(df["age"].max() - df["age"].min()))

df["spending_score_scaled"] = ((df["spending_score"] - df["spending_score"].min())/(df["spending_score"].max() - df["spending_score"].min()))

df["website_visits_scaled"] = ((df["website_visits_per_month"] - df["website_visits_per_month"].min())/(df["website_visits_per_month"].max() - df["website_visits_per_month"].min()))
df["avg_purchase_value_scaled"] = ((df["avg_purchase_value_usd"] - df  ["avg_purchase_value_usd"].min())/(df["avg_purchase_value_usd"].max() - df["avg_purchase_value_usd"].min()))
df["days_since_last_purchase_scaled"] = ((df["days_since_last_purchase"] - df["days_since_last_purchase"].min())/(df["days_since_last_purchase"].max() - df["days_since_last_purchase"].min()))

In [ ]:
df.describe()

,age,annual_income_usd,spending_score,website_visits_per_month,avg_purchase_value_usd,days_since_last_purchase,annual_income_scaled,age_scaled,spending_score_scaled,website_visits_scaled,avg_purchase_value_scaled,days_since_last_purchase_scaled
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,36.630435,74242.265000,58.710000,15.241935,219.620290,28.055000,0.206805,0.365303,0.520854,0.384917,0.297121,0.355987
std,12.287361,46990.867133,20.515612,7.553532,179.748451,15.941853,0.164038,0.240929,0.250190,0.204150,0.266117,0.209761
min,18.000000,15000.000000,16.000000,1.000000,18.930000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,25.000000,31979.250000,41.000000,10.000000,59.050000,17.750000,0.059272,0.137255,0.304878,0.243243,0.059397,0.220395
50%,36.630435,61616.500000,61.000000,15.000000,164.615000,26.000000,0.162731,0.365303,0.548780,0.378378,0.215686,0.328947
75%,45.000000,115724.500000,75.000000,20.000000,392.392500,37.000000,0.351613,0.529412,0.719512,0.513514,0.552909,0.473684
max,69.000000,301464.000000,98.000000,38.000000,694.380000,77.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000