In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('medical_data.csv')
df

    PatientID  FastingGlucose   BMI Smoking  HeartDisease
0           1              85  21.8      No             0
1           2              88  22.5      No             0
2           3              90  23.0     Yes             0
3           4              92  23.7      No             0
4           5              94  24.5     Yes             0
5           6              96  25.0      No             0
6           7              98  26.0     Yes             0
7           8             100  26.8      No             0
8           9             102  27.5     Yes             0
9          10             104  28.0      No             0
10         11             106  27.2      No             1
11         12             108  28.5     Yes             1
12         13             110  29.0      No             1
13         14             112  30.1     Yes             1
14         15             114  31.0     Yes             1
15         16             116  30.5      No             1
16         17             118  31.8     Yes             1
17         18             120  32.5     Yes             1
18         19             122  33.0      No             1
19         20             124  33.8     Yes             1
20         21             126  34.5     Yes             1
21         22             128  35.0      No             1
22         23             130  35.8     Yes             1
23         24             132  36.2     Yes             1
24         25             134  36.8      No             1
25         26             136  37.5     Yes             1
26         27             138  38.0     Yes             1
27         28             140  38.6      No             1
28         29             142  39.0     Yes             1
29         30             144  39.5     Yes             1
30         31             146  40.0      No             1
31         32             148  40.8     Yes             1
32         33             150  41.5     Yes             1
33         34             152  42.0      No             1
34         35             154  42.8     Yes             1
35         36             156  43.5     Yes             1
36         37             158  44.0      No             1
37         38             160  44.6     Yes             1
38         39             162  45.2     Yes             1
39         40             165  46.0     Yes             1

In [2]:
df["GlucoseGroup"] = df["FastingGlucose"].apply(lambda x:"Normal" if x<100 else "High")
df["BMIGroup"] = df["BMI"].apply(lambda x:"Normal" if x<25 else "Overweight")

In [3]:
df

,PatientID,FastingGlucose,BMI,Smoking,HeartDisease,GlucoseGroup,BMIGroup
0,1,85,21.8,No,0,Normal,Normal
1,2,88,22.5,No,0,Normal,Normal
2,3,90,23.0,Yes,0,Normal,Normal
3,4,92,23.7,No,0,Normal,Normal
4,5,94,24.5,Yes,0,Normal,Normal
5,6,96,25.0,No,0,Normal,Overweight
6,7,98,26.0,Yes,0,Normal,Overweight
7,8,100,26.8,No,0,High,Overweight
8,9,102,27.5,Yes,0,High,Overweight
9,10,104,28.0,No,0,High,Overweight
10,11,106,27.2,No,1,High,Overweight
11,12,108,28.5,Yes,1,High,Overweight
12,13,110,29.0,No,1,High,Overweight
13,14,112,30.1,Yes,1,High,Overweight
14,15,114,31.0,Yes,1,High,Overweight
15,16,116,30.5,No,1,High,Overweight
16,17,118,31.8,Yes,1,High,Overweight
17,18,120,32.5,Yes,1,High,Overweight
18,19,122,33.0,No,1,High,Overweight
19,20,124,33.8,Yes,1,High,Overweight
20,21,126,34.5,Yes,1,High,Overweight
21,22,128,35.0,No,1,High,Overweight
22,23,130,35.8,Yes,1,High,Overweight
23,24,132,36.2,Yes,1,High,Overweight
24,25,134,36.8,No,1,High,Overweight
25,26,136,37.5,Yes,1,High,Overweight
26,27,138,38.0,Yes,1,High,Overweight
27,28,140,38.6,No,1,High,Overweight
28,29,142,39.0,Yes,1,High,Overweight
29,30,144,39.5,Yes,1,High,Overweight
30,31,146,40.0,No,1,High,Overweight
31,32,148,40.8,Yes,1,High,Overweight
32,33,150,41.5,Yes,1,High,Overweight
33,34,152,42.0,No,1,High,Overweight
34,35,154,42.8,Yes,1,High,Overweight
35,36,156,43.5,Yes,1,High,Overweight
36,37,158,44.0,No,1,High,Overweight
37,38,160,44.6,Yes,1,High,Overweight
38,39,162,45.2,Yes,1,High,Overweight
39,40,165,46.0,Yes,1,High,Overweight

In [4]:
def calculate_entropy(series):
    probs = series.value_counts(normalize=True)
    return -np.sum(probs * np.log2(probs))

In [5]:
def calculate_conditional_entropy(df, feature, target):
    values = df[feature].unique()
    total_entropy = 0
    total_samples = len(df)
    
    for val in values:
        subset = df[df[feature] == val][target]
        weight = len(subset) / total_samples
        total_entropy += weight * calculate_entropy(subset)
    
    return total_entropy


print(calculate_entropy(df['HeartDisease']))
print(calculate_conditional_entropy(df, 'GlucoseGroup', 'HeartDisease'))

# features = [ 'GlucoseGroup','BMIGroup', 'Smoking']
# results = []

# for col in features:
#     h_y_x = calculate_conditional_entropy(df, col, 'HeartDisease')
#     mi = h_y - h_y_x
#     results.append({'Feature': col, 'H(Y|X)': h_y_x, 'MI': mi})

# results_df = pd.DataFrame(results)
# print("\nMutual Information Results : ")
# print(results_df)

0.8112781244591328
0.3625850142102485